// <auto-generated />
using System;
using Gamestore.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gamestore.DAL.Migrations
{
    [DbContext(typeof(GamestoreDbContext))]
    [Migration("20260404131327_NewGameFieldsForFiltration")]
    partial class NewGameFieldsForFiltration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gamestore.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("QuotedCommentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("QuotedCommentId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Gamestore.Domain.Entities.CommentBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BannedUntil")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPermanent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CommentBans");
                });

            modelBuilder.Entity("Gamestore.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("PublishDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UnitInStock")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("PublisherId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Gamestore.Domain.Entities.GameGenre", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GameGenres", (string)null);
                });

            modelBuilder.Entity("Gamestore.Domain.Entities.GamePlatform", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.ToTable("GamePlatforms", (string)null);
                });

            modelBuilder.Entity("Gamestore.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ParentGenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentGenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3fdfda42-5f9f-4f50-90a3-b0f9f4c83297"),
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = new Guid("fcdbd9b9-32e0-4190-964f-be636cc1ceb8"),
                            Name = "RTS",
                            ParentGenreId = new Guid("3fdfda42-5f9f-4f50-90a3-b0f9f4c83297")
                        },
                        new
                        {
                            Id = new Guid("2e98834a-1196-41e3-93b9-5dcf79c3504f"),
                            Name = "TBS",
                            ParentGenreId = new Guid("3fdfda42-5f9f-4f50-90a3-b0f9f4c83297")
                        },
                        new
                        {
                            Id = new Guid("e219b857-af30-4f06-97a7-23fca0b061f5"),
                            Name = "RPG"
                        },
                        new
                        {
                            Id = new Guid("10c8abd7-0901-4d25-96cd-460ed43b002b"),
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("6cc93ce8-8b02-489c-a2c0-5c45e12380cf"),
                            Name = "Races"
                        },
                        new
                        {
                            Id = new Guid("534f0bbc-8e8a-465a-9185-4eead9bb8881"),
                            Name = "Rally",
                            ParentGenreId = new Guid("6cc93ce8-8b02-489c-a2c0-5c45e12380cf")
                        },
                        new
                        {
                            Id = new Guid("826e499c-abe9-4f43-a7cc-6e6361b8eaf3"),
                            Name = "Arcade",
                            ParentGenreId = new Guid("6cc93ce8-8b02-489c-a2c0-5c45e12380cf")
                        },
                        new
                        {
                            Id = new Guid("08044742-f1b2-4e1e-be70-2c03077e3570"),
                            Name = "Formula",
                            ParentGenreId = new Guid("6cc93ce8-8b02-489c-a2c0-5c45e12380cf")
                        },
                        new
                        {
                            Id = new Guid("da7216d9-61e6-4b5f-989d-faee4a0df753"),
                            Name = "Off-road",
                            ParentGenreId = new Guid("6cc93ce8-8b02-489c-a2c0-5c45e12380cf")
                        },
                        new
                        {
                            Id = new Guid("58413a2f-534a-488e-8066-8f1e48611b35"),
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("52514583-2213-4dee-aabe-febfd2f95846"),
                            Name = "FPS",
                            ParentGenreId = new Guid("58413a2f-534a-488e-8066-8f1e48611b35")
                        },
                        new
                        {
                            Id = new Guid("3aea7cbc-edba-40d0-9709-5655f8476ef6"),
                            Name = "TPS",
                            ParentGenreId = new Guid("58413a2f-534a-488e-8066-8f1e48611b35")
                        },
                        new
                        {
                            Id = new Guid("fba94f42-23ef-4e20-9871-73c51852517a"),
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("f426ce2d-3f57-430e-9614-66e0313ba5a1"),
                            Name = "Puzzle & Skill"
                        });
                });

            modelBuilder.Entity("Gamestore.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Gamestore.Domain.Entities.OrderGame", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Discount")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderGames");
                });

            modelBuilder.Entity("Gamestore.Domain.Entities.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60dccf95-d657-4ec3-b9d1-01529b4c40d3"),
                            Type = "Mobile"
                        },
                        new
                        {
                            Id = new Guid("40429db0-1439-41aa-a420-73dccbdfdc3d"),
                            Type = "Browser"
                        },
                        new
                        {
                            Id = new Guid("fd1e5957-93bc-4a81-a76b-b219b1b76d3f"),
                            Type = "Desktop"
                        },
                        new
                        {
                            Id = new Guid("a76d2e28-ae0c-43c1-9e6e-5c75523ddc67"),
                            Type = "Console"
                        });
                });

            modelBuilder.Entity("Gamestore.Domain.Entities.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName")
                        .IsUnique();

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("Gamestore.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Gamestore.Domain.Entities.Game", "Game")
                        .WithMany("Comments")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gamestore.Domain.Entities.Comment", "ParentComment")
                        .WithMany("ChildComments")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Gamestore.Domain.Entities.Comment", "QuotedComment")
                        .WithMany("QuotedByComments")
                        .HasForeignKey("QuotedCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Game");

                    b.Navigation("ParentComment");

                    b.Navigation("QuotedComment");
                });

            modelBuilder.Entity("Gamestore.Domain.Entities.Game", b =>
                {
                    b.HasOne("Gamestore.Domain.Entities.Publisher", "Publisher")
                        .WithMany("Games")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Gamestore.Domain.Entities.GameGenre", b =>
                {
                    b.HasOne("Gamestore.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gamestore.Domain.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gamestore.Domain.Entities.GamePlatform", b =>
                {
                    b.HasOne("Gamestore.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gamestore.Domain.Entities.Platform", null)
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gamestore.Domain.Entities.Genre", b =>
                {
                    b.HasOne("Gamestore.Domain.Entities.Genre", "ParentGenre")
                        .WithMany("SubGenres")
                        .HasForeignKey("ParentGenreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentGenre");
                });

            modelBuilder.Entity("Gamestore.Domain.Entities.OrderGame", b =>
                {
                    b.HasOne("Gamestore.Domain.Entities.Order", "Order")
                        .WithMany("OrderGames")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gamestore.Domain.Entities.Game", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Gamestore.Domain.Entities.Comment", b =>
                {
                    b.Navigation("ChildComments");

                    b.Navigation("QuotedByComments");
                });

            modelBuilder.Entity("Gamestore.Domain.Entities.Game", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Gamestore.Domain.Entities.Genre", b =>
                {
                    b.Navigation("SubGenres");
                });

            modelBuilder.Entity("Gamestore.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderGames");
                });

            modelBuilder.Entity("Gamestore.Domain.Entities.Publisher", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
